const PERMISSIONS = {
    DASHBOARD_VIEW: 'dashboard.view',
    SKILLS_VIEW: 'skills.view',
    SKILLS_EDIT: 'skills.edit',
    PROJECTS_VIEW: 'projects.view',
    PROJECTS_EDIT: 'projects.edit',
    STUDY_VIEW: 'study.view',
    STUDY_EDIT: 'study.edit',
    DEADLINES_VIEW: 'deadlines.view',
    DEADLINES_EDIT: 'deadlines.edit',
    ACTIVITY_VIEW: 'activity.view',
    ACTIVITY_EDIT: 'activity.edit',
    USERS_VIEW: 'users.view',
    USERS_EDIT: 'users.edit',
    USERS_DELETE: 'users.delete',
    ROLES_MANAGE: 'roles.manage',
    ADMINS_MANAGE: 'admins.manage',
    ANALYTICS_VIEW: 'analytics.view',
    SYSTEM_SETTINGS: 'system.settings',
    AUDIT_VIEW: 'audit.view',
    CONTENT_PUBLISH: 'content.publish',
    CONTENT_DELETE: 'content.delete'
};

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

const ROLES = {
    SUPER_ADMIN: 'SuperAdmin',
    ADMIN: 'Admin',
    EDITOR: 'Editor',
    MODERATOR: 'Moderator',
    CONTENT_MANAGER: 'ContentManager',
    SUPPORT: 'Support',
    ANALYTICS: 'Analytics',
    READ_ONLY: 'ReadOnly',
    USER: 'User',
    VISITOR: 'Visitor'
};

const DEFAULT_ROLE_PERMISSIONS = {
    [ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,
    [ROLES.ADMIN]: ALL_PERMISSIONS.filter(p => p !== PERMISSIONS.ROLES_MANAGE),
    [ROLES.EDITOR]: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.SKILLS_VIEW,
        PERMISSIONS.SKILLS_EDIT,
        PERMISSIONS.PROJECTS_VIEW,
        PERMISSIONS.PROJECTS_EDIT,
        PERMISSIONS.STUDY_VIEW,
        PERMISSIONS.STUDY_EDIT,
        PERMISSIONS.DEADLINES_VIEW,
        PERMISSIONS.DEADLINES_EDIT,
        PERMISSIONS.ACTIVITY_VIEW,
        PERMISSIONS.ACTIVITY_EDIT,
        PERMISSIONS.CONTENT_PUBLISH
    ],
    [ROLES.MODERATOR]: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.USERS_VIEW,
        PERMISSIONS.CONTENT_PUBLISH,
        PERMISSIONS.CONTENT_DELETE
    ],
    [ROLES.CONTENT_MANAGER]: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.SKILLS_VIEW,
        PERMISSIONS.SKILLS_EDIT,
        PERMISSIONS.PROJECTS_VIEW,
        PERMISSIONS.PROJECTS_EDIT,
        PERMISSIONS.STUDY_VIEW,
        PERMISSIONS.STUDY_EDIT,
        PERMISSIONS.DEADLINES_VIEW,
        PERMISSIONS.DEADLINES_EDIT,
        PERMISSIONS.ACTIVITY_VIEW,
        PERMISSIONS.ACTIVITY_EDIT,
        PERMISSIONS.CONTENT_PUBLISH,
        PERMISSIONS.CONTENT_DELETE
    ],
    [ROLES.SUPPORT]: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.USERS_VIEW,
        PERMISSIONS.USERS_EDIT
    ],
    [ROLES.ANALYTICS]: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.ANALYTICS_VIEW
    ],
    [ROLES.READ_ONLY]: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.SKILLS_VIEW,
        PERMISSIONS.PROJECTS_VIEW,
        PERMISSIONS.STUDY_VIEW,
        PERMISSIONS.DEADLINES_VIEW,
        PERMISSIONS.ACTIVITY_VIEW,
        PERMISSIONS.USERS_VIEW,
        PERMISSIONS.ANALYTICS_VIEW,
        PERMISSIONS.AUDIT_VIEW
    ],
    [ROLES.USER]: [],
    [ROLES.VISITOR]: []
};

module.exports = {
    PERMISSIONS,
    ALL_PERMISSIONS,
    ROLES,
    DEFAULT_ROLE_PERMISSIONS
};
